# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPruebaRegistro():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_pruebaRegistro(self):
    self.driver.get("https://demo.guru99.com/test/newtours/register.php")
    self.driver.set_window_size(652, 678)
    self.driver.find_element(By.NAME, "firstName").click()
    self.driver.find_element(By.NAME, "firstName").send_keys("Marvelis")
    self.driver.find_element(By.NAME, "lastName").send_keys("Amaris")
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("marvelis134@gmail.com")
    self.driver.find_element(By.NAME, "password").send_keys("Medellin123.")
    self.driver.find_element(By.NAME, "confirmPassword").send_keys("Medellin123.")
    self.driver.find_element(By.NAME, "submit").click()
    self.driver.execute_script("window.scrollTo(0,300)")
  
